name: API CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

concurrency:
  group: api-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      # (Optionnel mais évite un warning "buildx isn't installed")
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node (for Newman)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman + HTML reporter
        run: npm i -g newman newman-reporter-htmlextra

      - name: Start stack (Docker Compose)
        run: |
          docker compose version || docker-compose --version
          # Lance le stack (si ton runner a uniquement docker-compose v1, tu peux remplacer la ligne suivante)
          docker compose up -d --build || docker-compose up -d --build
          echo "Wait for API health..."
          for i in {1..30}; do
            if curl -sf http://localhost:8000/healthz >/dev/null; then
              echo "API is up"; break
            fi
            sleep 2
          done
          curl -sf http://localhost:8000/healthz && echo

      - name: Run Smoke — User flow
        run: |
          newman run postman/GenXTrack_Auth_API_Automated_v2.postman_collection.json \
            -e postman/GenXTrack_Auth_Automated.postman_environment.json \
            --folder "Smoke — User flow" \
            -r cli,htmlextra --reporter-htmlextra-export newman-smoke-user.html

      - name: Run Smoke — Admin flow
        run: |
          newman run postman/GenXTrack_Auth_API_Automated_v2.postman_collection.json \
            -e postman/GenXTrack_Auth_Automated.postman_environment.json \
            --folder "Smoke — Admin flow" \
            -r cli,htmlextra --reporter-htmlextra-export newman-smoke-admin.html

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: |
            newman-smoke-user.html
            newman-smoke-admin.html

      - name: Dump compose status & logs on failure
        if: failure()
        run: |
          docker compose ps || docker-compose ps
          docker compose logs --no-color || docker-compose logs
